In [48]:
import pandas as pd
import numpy as np
import random

## Exercise 1 : Array Creation and Manipulation

**Instructions**
- Create a 1D NumPy array containing numbers from 0 to 9.

In [39]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Exercise 2 : Type Conversion and Array Operations

**Instructions**
- Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [40]:
num_list = [3.14, 2.17, 0, 1, 2] # create a list
type(num_list)

list

In [41]:
num_array = np.array(num_list) # convert this list to numpy array
type(num_array)
num_array

array([3.14, 2.17, 0.  , 1.  , 2.  ])

In [11]:
num_array_int = num_array.astype(int) # converting date type to integer
num_array_int.dtype
num_array_int

array([3, 2, 0, 1, 2])

## Exercise 3 : Working with Multi-Dimensional Arrays

**Instructions**
- Create a 3x3 NumPy array with values ranging from 1 to 9.

In [45]:
# option 1 - to create it manually 

three_array = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

three_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
# option 2 - to create it with arange() and reshape() 

three_array_2 = np.arange(1,10).reshape(3,3)
three_array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

**Instructions**
- Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [24]:
# option 1 - to create it manually 

md_array = np.array([[23, 43, 53, 26, 76],
                     [12, 34, 19, 3, 14],
                     [99, 36, 21, 30, 55],
                     [100, 15, 17, 27, 81]
                    ])
md_array.shape
md_array

array([[ 23,  43,  53,  26,  76],
       [ 12,  34,  19,   3,  14],
       [ 99,  36,  21,  30,  55],
       [100,  15,  17,  27,  81]])

In [54]:
# option 2 - to create it with np.random.randint(start, end, size = (size of 2d numpy))

md_array_2 = np.random.randint(10, 50, size = (4,5))
md_array_2

array([[40, 27, 24, 14, 14],
       [43, 11, 36, 29, 10],
       [44, 43, 39, 49, 38],
       [30, 25, 35, 28, 36]], dtype=int32)

## Exercise 5 : Indexing Arrays

**Instructions**
- Select the second row from a given 2D NumPy array.

In [25]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array[2]

array([21, 22, 23, 22, 22])

## Exercise 6 : Reversing elements

**Instructions**
- Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [28]:
num_array = np.arange(10)
num_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Exercise 7 : Identity Matrix

**Instructions**
- Create a 4x4 identity matrix using NumPy.

In [34]:
# option 1 - to create it manually and convert to the float

matrix = np.array([[1, 0, 0, 0],
                   [0, 1, 0, 0],
                   [0, 0, 1, 0],
                   [0, 0, 0, 1]])

matrix = matrix.astype(float)
matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
# option 2 - to create it with a function

matrix = np.eye(4)

matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Exercise 8 : Simple Aggregate Funcs

**Instructions**
- Find the sum and average of a given 1D array.

In [66]:
array = np.arange(10)
np.sum(array) # sum of the array

np.int64(45)

In [67]:
np.mean(array) # average of the array

np.float64(4.5)

## Exercise 9 : Create Array and Change its Structure

**Instructions**
- Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [58]:
num_array = np.arange(1, 21) # creat numpyarray from 1 to 20
num_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [63]:
num_array_mat = num_array.reshape(4,5) # create matrix with reshape()
num_array_mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Exercise 10 : Conditional Selection of Values

**Instructions**
- Extract all odd numbers from a given NumPy array.

In [69]:
array = np.arange(10)
odd_numbers = array[array % 2 !=0]
odd_numbers

array([1, 3, 5, 7, 9])