In [2]:
import pandas as pd
import numpy as np
import random

## Exercise 1 : Minimum and Maximum of Random Array
Create a 5x5 array with random values and find the minimum and maximum values.

In [16]:
np.random.seed(42) # data will never change
array = np.random.uniform(1, 50, size = (5,5)).round(2) # create random numbers and round them
max_array = np.max(array) # count max
min_array = np.min(array) # count min

print(f'Min: {min_array}, Max: {max_array}') # print the result

Min: 2.01, Max: 48.53


## Exercise 2 : Matrix Normalization
Normalize a 3x3 random matrix (subtract the mean and divide by the standard deviation of the matrix).

In [27]:
np.random.seed(42) # data will never change
array = np.random.uniform(25, 60, size = (3,3)).round(2) # create random numbers and round them
array

array([[38.11, 58.28, 50.62],
       [45.95, 30.46, 30.46],
       [27.03, 55.32, 46.04]])

In [32]:
std_array = array.std() # count std
std_array

np.float64(10.812747734976845)

In [33]:
mean_array = array.mean() # count mean
mean_array

np.float64(42.474444444444444)

In [34]:
norm_array = (array - mean_array) / std_array # normalize array
norm_array

array([[-0.40363879,  1.46175199,  0.75332892],
       [ 0.3214313 , -1.11113703, -1.11113703],
       [-1.4283552 ,  1.18800104,  0.32975481]])

## Exercise 3 : Evenly Spaced Elements in Array
Create a 1D array of 50 evenly spaced elements between 0 and 10, exclusive.

In [37]:
array_1d = np.linspace(0,10,50).round(1) # create 1D array of 50 evenly spaced elements between 0 and 10, exclusive with linspace and round them
array_1d

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,
        9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

## Exercise 4 : Matrix Multiplication
Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [40]:
np.random.seed(42) # data will never change
matrix_a = np.random.uniform(1, 50, size = (5,3)).round(1)  # create random numbers and round them
matrix_a

array([[19.4, 47.6, 36.9],
       [30.3,  8.6,  8.6],
       [ 3.8, 43.4, 30.5],
       [35.7,  2. , 48.5],
       [41.8, 11.4,  9.9]])

In [42]:
np.random.seed(41) # data will never change
matrix_b = np.random.uniform(1, 50, size = (3,2)).round(1)  # create random numbers and round them
matrix_b

array([[13.3,  3.3],
       [34.2,  3.1],
       [ 6.7, 30.6]])

In [44]:
# Matrix multiplication
result = matrix_a @ matrix_b
result

array([[2133.17, 1340.72],
       [ 754.73,  389.81],
       [1739.17, 1080.38],
       [ 868.16, 1608.11],
       [1012.15,  476.22]])

In [46]:
print(f'Matrix A: {matrix_a}')
print(f'Matrix B: {matrix_b}')
print(f'Matrix Multiplication Result: {result}')

Matrix A: [[19.4 47.6 36.9]
 [30.3  8.6  8.6]
 [ 3.8 43.4 30.5]
 [35.7  2.  48.5]
 [41.8 11.4  9.9]]
Matrix B: [[13.3  3.3]
 [34.2  3.1]
 [ 6.7 30.6]]
Matrix Multiplication Result: [[2133.17 1340.72]
 [ 754.73  389.81]
 [1739.17 1080.38]
 [ 868.16 1608.11]
 [1012.15  476.22]]


## Exercise 5

In [47]:
np.random.seed(42) # data will never change
matrix_a = np.random.uniform(1, 50, size = (6,7)).round(1)  # create random numbers and round them
matrix_a

array([[19.4, 47.6, 36.9, 30.3,  8.6,  8.6,  3.8],
       [43.4, 30.5, 35.7,  2. , 48.5, 41.8, 11.4],
       [ 9.9, 10. , 15.9, 26.7, 22.2, 15.3, 31. ],
       [ 7.8, 15.3, 19. , 23.3, 39.5, 10.8, 26.2],
       [30. ,  3.3, 30.8,  9.4,  4.2, 47.5, 48.3],
       [40.6, 15.9,  5.8, 34.5, 22.6,  7. , 25.3]])

In [48]:
np.random.seed(41) # data will never change
matrix_b = np.random.uniform(1, 50, size = (7,3)).round(1)  # create random numbers and round them
matrix_b

array([[13.3,  3.3, 34.2],
       [ 3.1,  6.7, 30.6],
       [10.4, 33.8, 46. ],
       [21.5, 17.3, 14.9],
       [10.1, 16.5, 24.6],
       [ 4.4, 35.5, 16.4],
       [37.5, 20.5, 30.8]])

In [49]:
# Matrix multiplication
result = matrix_a @ matrix_b
result

array([[1707.99, 2679.45, 4738.55],
       [2187.32, 4106.68, 6319.32],
       [2356.12, 2643.95, 3525.65],
       [2278.69, 2745.79, 3911.89],
       [2994.32, 4070.47, 5053.8 ],
       [2599.15, 2173.45, 4105.91]])